<?php

return [
	[
		'name' => 'Credit Evaluator Plus&trade;',
		'code' => 'cep',
		'short_description' => 'Make Credit Decisions Simple',
		"description_title" => 'Basic Business Report for Simple Credit Decisions',
		'description' => 'Quickly help you determine a company\'s risk of late payment and identify how much credit to extend based on a company\'s D&amp;B PAYDEX&reg; Score, D&amp;B Credit Limit Recommendation, and past payment behavior',
		'call_to_action' => 'Add to Cart',
		'phone' => false,
		'sell_on_mobile' => false,
		'bullets' => [
			'D&amp;B PAYDEX&reg; Score',
			'Risk of late payment indicator',
			'D&amp;B&reg; Credit Limit Recommendation',
			'12 months of alerts with change notifications',
		],
		'compare_bullets' => [
			'24/7 online access',
			'D&amp;B PAYDEX&reg; Score',
			'Risk of late payment indicator',
			'D&amp;B&reg; Credit Limit Recommendation'
		],
		'included' => [
			'24/7 online access',
			'D&amp;B PAYDEX&reg; Score',
			'Risk assessment',
			'Risk of late payment indicator',
			'D&amp;B&reg; Credit Limit Recommendations',
			'12 months of alerts',
			'Payment trends',
		],
		'quantity' => [
			[
				'product_id' => 3317,
				'price_id' => 5509,
				'count' => 1,
				'short_description' => 'Report for one company',
				'price' => [
					'dollars' => 61,
					'cents' => 99,
				],
			],
			[
				'product_id' => 5014,
				'price_id' => 5511,
				'count' => 5,
				'short_description' => 'Report for 5 companies',
				'price' => [
					'dollars' => 224,
					'cents' => 99,
				],
			],
			[
				'product_id' => 5015,
				'price_id' => 5512,
				'count' => 10,
				'short_description' => 'Report for 10 companies',
				'price' => [
					'dollars' => 514,
					'cents' => 99,
				],
			],
		],
	],
	[
		'name' => 'Business Information Report&trade;',
		'code' => 'bir',
		'short_description' => 'Most Popular Business Report',
		'description_title' => 'The Most Popular Report for Business Credit Decisions',
		'description' => 'Use this detailed one-time report to help mitigate potential business risks by accessing a company\'s operations, financial, and public filing records. Help avoid payment defaults and assess a company\'s business risk with straightforward risk indicators like the D&amp;B PAYDEX&reg; Score, D&amp;B Viability Rating, and D&amp;B Rating.',
		'call_to_action' => 'Add to Cart',
		'phone' => false,
		'sell_on_mobile' => false,
		'bullets' => [
			'D&amp;B PAYDEX&reg; Score',
			'D&amp;B&reg; Credit Limit Recommendation',
			'D&amp;B Viability Rating&reg;',
			'D&amp;B&reg; Rating',
		],
		'compare_bullets' => [
			'D&amp;B Viability Rating&reg;',
			'Industry trends',
			'Detailed company profile',
			'D&amp;B&reg; Rating'
		],
		'included' => [
			'24/7 online access',
			'D&amp;B PAYDEX&reg; Score',
			'Risk assessment',
			'Risk of late payment indicator',
			'D&amp;B&reg; Credit Limit Recommendations',
			'12 months of alerts',
			'D&amp;B Viability Rating&reg;',
			'Industry trends',
			'Payment trends',
			'Detailed company profile',
			'D&amp;B&reg; Rating',
		],
		'quantity' => [
			[
				'product_id' => 3315,
				'price_id' => 5505,
				'count' => 1,
				'short_description' => 'Report for one company',
				'price' => [
					'dollars' => 121,
					'cents' => 99,
				],
			],
			[
				'product_id' => 5011,
				'price_id' => 5507,
				'count' => 5,
				'short_description' => 'Report for 5 companies',
				'price' => [
					'dollars' => 554,
					'cents' => 99,
				],
			],
			[
				'product_id' => 5012,
				'price_id' => 5508,
				'count' => '10',
				'short_description' => 'Report for 10 companies',
				'price' => [
					'dollars' => 1024,
					'cents' => 99,
				],
			],
		],
	],
	[
		'name' => 'Credit Advisor&trade;',
		'code' => 'ca',
		'short_description' => 'Continuous Access to Credit Data ',
		'description_title' => 'Continuous Monitoring of a Company for a Full Year',
		'description' => 'Continuous, real-time access to a company\'s credit file can help you make confident credit decisions and proactively manage credit relationships. Help reduce your exposure to bad debt and maintain a healthy cash flow with 24/7 access to D&amp;B&reg; scores and ratings, receiving email alerts when changes occur in a company\'s business credit file.',
		'call_to_action' => 'Add to Cart',
		'phone' => false,
		'sell_on_mobile' => false,
		'bullets' => [
			'Six D&amp;B&reg; scores and ratings',
			'Business event notifications',
			'Financial Statements',
			'Corporate linkage',
		],
		'compare_bullets' => [
			'Risk assessment',
			'D&amp;B&reg; Financial Stress Score',
			'D&amp;B&reg; Delinquency Predictor Score',
			'D&amp;B&reg; Supplier Evaluation Risk Rating'
		],
		'included' => [
			'24/7 online access',
			'D&amp;B PAYDEX&reg; Score',
			'12 months of alerts',
			'D&amp;B&reg; Rating',
			'D&amp;B&reg; Financial Stress Score',
			'D&amp;B&reg; Delinquency Predictor Score',
			'Business event notifications',
			'Financial statements',
			'Corporate Linkage',
			'D&amp;B&reg; Supplier Evaluation Risk Rating',
			'Unlimited and continuous access',
			'Custom data archives',
		],
		'quantity' => [
			[
				'product_id' => 3313,
				'price_id' => 15,
				'count' => 1,
				'short_description' => 'Report for one company',
				'price' => [
					'dollars' => 188,
					'cents' => '00',
				],
			],
			[
				'product_id' => 5009,
				'price_id' => 5017,
				'count' => 5,
				'short_description' => 'Report for 5 companies',
				'price' => [
					'dollars' => 578,
					'cents' => '00',
				],
			],
			[
				'product_id' => 5010,
				'price_id' => 5018,
				'count' => 10,
				'short_description' => 'Report for 10 companies',
				'price' => [
					'dollars' => 1579,
					'cents' => '00',
				],
			],
		],
	],
	[
		'name' => 'D&amp;B Credit',
		'code' => 'dnbc',
		'short_description' => 'Evaluate multiple companies',
		'description_title' => 'The Most Comprehensive Credit Risk Management Solution',
		'description' => 'Easily and effectively manage your business credit and risk decisions with D&amp;B\'s next-generation credit risk management solution. With instant access to the world\'s largest business credit database, you can proactively monitor your company\'s business risk exposure based on your customers\' business credit profiles. Custom alerts about changes to a company\'s business credit risk can help you protect your company\'s cash flow and minimize potential bad debt write-offs.',
		'call_to_action' => 'Call Us (800) 372-2733',
		'phone' => '(800) 372-2733',
		'sell_on_mobile' => true,
		'bullets' => [
			'Failure Risk',
			'Delinquency Risk',
			'D&amp;B PAYDEX&reg; Score',
			'Maximum Credit Recommendation',
		],
		'compare_bullets' => [
			'Financial statements',
			'Unlimited and continuous access',
			'Custom data archives',
			'Evaluate multiple companies',
		],
		'included' => [
			'24/7 online access',
			'D&amp;B PAYDEX&reg; Score',
			'12 months of alerts',
			'D&amp;B&reg; Rating',
			'D&amp;B&reg; Financial Stress Score',
			'D&amp;B&reg; Delinquency Predictor Score',
			'Business event notifications',
			'Financial statements',
			'Corporate Linkage',
			'D&amp;B&reg; Supplier Evaluation Risk Rating',
			'Unlimited and continuous access',
			'Custom data archives',
			'Evaluate multiple companies',
		],
		'quantity' => [
			[
				'product_id' => null,
				'price_id' => null,
				'count' => 1,
				'short_description' => 'Call for options',
				'price' => [
					'dollars' => null,
					'cents' => null,
				],
			],
		],
	],
];
