<?php

return [
	[
		'name' => 'CreditSignal&reg;',
		'code' => 'cs',
		'short_description' => 'Free Alerts',
		'description_title' => 'Free Access to Changes in your D&amp;B&reg; Scores and Ratings&reg;',
		'description' => 'Monitor changes to your D&B scores and ratings and help ensure you have the most up-to-date business credit information on your company. Help anticipate possible reactions from current partners and lenders, track how many times your report is being accessed, and know when to take action to help impact your file.',
		'call_to_action' => 'Sign Up for Free',
		'phone' => false,
		'sell_on_mobile' => true,
		'bullets' => [
				'D&amp;B scores and ratings change alerts',
				'Inquiry alerts&#8224;',
				'Special event alerts',
				'Mobile access to CreditReporter&trade;',
		],
		'compare_bullets' => [
			'Alert of Changes',
			'24/7 online access',
			'Mobile access to CreditReporter&trade;',
			'Access your D&amp;B scores &amp; ratings',
		],
		'included' => [
			'Alerts of Changes',
			'24/7 online access',
			'Mobile access to CreditReporter&trade;',
			'Inquiry alerts&#42;',
			'Access your D&amp;B scores &amp; ratings',
		],
		'quantity' => [
			[
				'product_id' => 6052,
				'price_id' => 6560,
				'count' => 1,
				'short_description' => 'Report for one company',
				'savings' => 0,
				'price' => [
					'dollars' => 0,
					'cents' => 0,
					'per' => null,
				],
			],
		],
	],
	[
		'name' => 'CreditMonitor&trade;',
		'code' => 'cm',
		'short_description' => 'Real-Time Monitoring',
		'description_title' => 'Real-Time Monitoring of Your D&amp;B&reg; Scores and Ratings',
		'description' => 'Take control of your business credit with real-time access to your scores and ratings, including your D&amp;B PAYDEX&reg; Score, with the ability to benchmark your scores against your industry. Know where your company stands and get valuable insight to help you protect and grow your business.',
		'call_to_action' => 'Add to Cart',
		'phone' => false,
		'sell_on_mobile' => false,
		'bullets' => [
				'Unlimited access to your D&amp;B&reg; scores and ratings',
				'Industry benchmarking',
				'Receive alerts to changes in your D&amp;B business credit file',
				'Expedited D&amp;B D-U-N-S&reg; Number',
		],
		'compare_bullets' => [
			'Access your D&amp;B scores &amp; ratings',
			'Expedited D&amp;B D-U-N-S&reg; Number',
			'Business event notifications',
			'Industry benchmarking',
		],
		'included' => [
			'Alerts of Changes',
			'24/7 online access',
			'Mobile access to CreditReporter&trade;',
			'Access your D&amp;B scores &amp; ratings',
			"Expedited <br> D&amp;B D-U-N-S&reg; Number",
			'Business event notifications',
			'Industry benchmarking',
		],
		'quantity' => [
			[
				'product_id' => 3202,
				'price_id' => 8872,
				'count' => 1,
				'short_description' => 'Report for one company',
				'savings' => 0,
				'price' => [
					'dollars' => 49,
					'cents' => '00',
					'per' => 'mo',
				],
			],
		],
	],
	[
		'name' => 'CreditBuilder&trade;',
		'code' => 'cb',
		'short_description' => 'Impact Your Business Credit',
		'description_title' => 'Take Action to Build Your Business Credit',
		'description' => 'Establish and build your D&amp;B&reg; credit file by submitting good payment history† that could otherwise go unreported to D&amp;B. This, along with the ability to dispute inaccurate information and comparatively benchmark of your scores against your industry and competitors, can help you build a stronger business credit file, which may improve your chances to qualify for a loan, attract new customers, and increase cash flow.',
		'call_to_action' => 'Add to Cart',
		'phone' => false,
		'sell_on_mobile' => false,
		'bullets' => [
			'Unlimited access to your D&amp;B&reg; scores and ratings',
			'Add trade references&#8224;&#8224; to your business credit file',
			'Get alerts when others buy your business credit report&#8224;',
			'Industry and peer benchmarking against your industry norms',
		],
		'compare_bullets' => [
			'Inquiry alerts&#42;',
			'Detail on inquiry alerts&#42;',
			'Peer benchmarking',
			'Add good payment history&#42;&#42;',
		],
		'included' => [
			'Alerts of Changes',
			'24/7 online access',
			'Mobile access to CreditReporter&trade;',
			'Inquiry alerts&#42;',
			'Detail on inquiry alerts&#42;',
			'Access your D&amp;B scores &amp; ratings',
			"Expedited <br> D&amp;B D-U-N-S&reg; Number",
			'Business event notifications',
			'Industry benchmarking',
			'Peer benchmarking',
			'Add good payment history&#42;&#42;',
		],
		'quantity' => [
			[
				'product_id' => 5002,
				'price_id' => 5003,
				'count' => 1,
				'short_description' => 'Report for one company',
				'savings' => 0,
				'price' => [
					'dollars' => 99,
					'cents' => '00',
					'per' => 'mo',
				],
			],
		],
	],
	[
		'name' => 'Credibility Concierge&reg;',
		'code' => 'cc',
		'short_description' => 'Evaluate multiple companies',
		'description_title' => 'You take care of business while we help you manage your business credit',
		'description' => 'Get a dedicated Credibility Concierge for professional account management. Your Concierge can help you impact your D&amp;B business credit file by fast-tracking important business credit report updates, disputing discrepancies in your payment history, suits, liens, and judgments to ensure your business credit file is complete, and providing one-on-one consultations‡ to help you make the best credit decisions for your company.',
		'call_to_action' => 'Call Us (800) 843-2677',
		'phone' => '(800) 843-2677',
		'sell_on_mobile' => true,
		'bullets' => [
			'Comprehensive Insight Plus Reports',
			'D&amp;B Credibility Review&trade; Platinum',
			'VERIFIED&trade; Premium',
			'Business Information Reports',
		],
		'compare_bullets' => [
			'CreditBuilder&trade; Premium with Credit Comparison Pack',
			'Dedicated team of business credit experts',
			'D&amp;B Credibility Review&trade; Platinum',
			'VERIFIED&trade; Premium'
		],
		'included' => [
			'Alerts of Changes',
			'24/7 online access',
			'Detail on inquiry alerts&#42;',
			'Access your D&amp;B scores &amp; ratings',
			'Industry benchmarking',
			'Peer benchmarking',
			'Add good payment history&#42;&#42;',
			'CreditBuilder&trade; Premium with Credit Comparison Pack',
			'Dedicated team of business credit experts',
			'D&amp;B Credibility Review&trade; Platinum',
			'VERIFIED&trade; Premium',
			'Business Information Reports',
		],
		'quantity' => [
			[
				'product_id' => 7200,
				'price_id' => null,
				'count' => 1,
				'short_description' => 'Call for options',
				'savings' => 0,
				'price' => [
					'dollars' => null,
					'cents' => null,
					'per' => null,
				],
			],
		],
	],
];
