<?php

return [
	[
		'name' => 'Product 5',
		'code' => 'product1',
		'short_description' => 'Product 5 Short Description',
		"description_title" => 'Product 5 Description Title',
		'description' => 'Quickly help you determine a company\'s risk and identify how much credit to extend based on a company\'s verified history and past payment behavior',
		'call_to_action' => 'Add to Cart',
		'phone' => false,
		'sell_on_mobile' => false,
		'bullets' => [
			'Company Score',
			'Risk of late payment indicator',
			'Company cCredit Limit Recommendation',
			'12 months of alerts with change notifications',
		],
		'compare_bullets' => [
			'24/7 online access',
			'Company Score',
			'Risk of late payment indicator',
			'Company Credit Limit Recommendation'
		],
		'included' => [
			'24/7 online access',
			'Company Score',
			'Risk assessment',
			'Risk of late payment indicator',
			'Company Credit Limit Recommendations',
			'12 months of alerts',
			'Payment trends',
		],
		'quantity' => [
			[
				'product_id' => 1000,
				'price_id' => 1000,
				'count' => 1,
				'short_description' => 'Monthly Subscription',
				'price' => [
					'dollars' => 49,
					'cents' => 99,
				],
			],
			[
				'product_id' => 1050,
				'price_id' => 1050,
				'count' => 5,
				'short_description' => 'Annual Subscription',
				'price' => [
					'dollars' => 499,
					'cents' => 99,
				],
			],
		],
	],
	[
		'name' => 'Product 6',
		'code' => 'product2',
		'short_description' => 'Product 2 Business Report',
		'description_title' => 'The Most Popular Report for Business Credit Decisions',
		'description' => 'Use this detailed one-time report to help mitigate potential business risks by accessing a company\'s operations, financial, and public filing records. Help avoid payment defaults and assess a company\'s business risk with straightforward risk indicators like the Company Score',
		'call_to_action' => 'Add to Cart',
		'phone' => false,
		'sell_on_mobile' => false,
		'bullets' => [
			'Company Score',
			'Credit Limit Recommendation',
			'Company Rating',
			'Company Rating',
		],
		'compare_bullets' => [
			'Company Rating&reg;',
			'Industry trends',
			'Detailed company profile',
			'Company Rating'
		],
		'included' => [
			'24/7 online access',
			'Company Score',
			'Risk assessment',
			'Risk of late payment indicator',
			'Credit Limit Recommendations',
			'12 months of alerts',
			'Company Rating&reg;',
			'Industry trends',
			'Payment trends',
			'Detailed company profile',
			'Second Rating',
		],
		'quantity' => [
			[
				'product_id' => 2000,
				'price_id' => 2000,
				'count' => 1,
				'short_description' => 'Report for one company',
				'price' => [
					'dollars' => 200,
					'cents' => 99,
				],
			],
			[
				'product_id' => 2050,
				'price_id' => 2050,
				'count' => 5,
				'short_description' => 'Report for 5 companies',
				'price' => [
					'dollars' => 449,
					'cents' => 99,
				],
			],
			[
				'product_id' => 2100,
				'price_id' => 2100,
				'count' => '10',
				'short_description' => 'Report for 10 companies',
				'price' => [
					'dollars' => 224,
					'cents' => 99,
				],
			],
		],
	],
	[
		'name' => 'Product 7',
		'code' => 'product3',
		'short_description' => 'Product 3 short Description',
		'description_title' => 'Product 3 title',
		'description' => 'Continuous, real-time access to a company\'s credit file can help you make confident credit decisions and proactively manage credit relationships. Help reduce your exposure to bad debt and maintain a healthy cash flow with 24/7 access to D&amp;B&reg; scores and ratings, receiving email alerts when changes occur in a company\'s business credit file.',
		'call_to_action' => 'Add to Cart',
		'phone' => false,
		'sell_on_mobile' => false,
		'bullets' => [
			'Six Companyscores and ratings',
			'Business event notifications',
			'Financial Statements',
			'Corporate linkage',
		],
		'compare_bullets' => [
			'Risk assessment',
			'Company Financial Stress Score',
			'Company Delinquency Predictor Score',
			'Company Supplier Evaluation Risk Rating'
		],
		'included' => [
			'24/7 online access',
			'Company Business Score',
			'12 months of alerts',
			'Company Business Rating',
			'Company Business Financial Stress Score',
			'Company Business Delinquency Predictor Score',
			'Business event notifications',
			'Financial statements',
			'Corporate Linkage',
			'Company Supplier Evaluation Risk Rating',
			'Unlimited and continuous access',
			'Custom data archives',
		],
		'quantity' => [
			[
				'product_id' => 3000,
				'price_id' => 3000,
				'count' => 1,
				'short_description' => 'Report for one company',
				'price' => [
					'dollars' => 199,
					'cents' => '00',
				],
			],
			[
				'product_id' => 8000,
				'price_id' => 8000,
				'count' => 5,
				'short_description' => 'Report for 5 companies',
				'price' => [
					'dollars' => 275,
					'cents' => '00',
				],
			],
			[
				'product_id' => 9000,
				'price_id' => 9000,
				'count' => 10,
				'short_description' => 'Report for 10 companies',
				'price' => [
					'dollars' => 1200,
					'cents' => '00',
				],
			],
		],
	],
	[
		'name' => 'Product 8',
		'code' => 'dnbc',
		'short_description' => 'Evaluate multiple companies',
		'description_title' => 'The Most Comprehensive Credit Risk Management Solution',
		'description' => 'Easily and effectively manage your business credit and risk decisions with D&amp;B\'s next-generation credit risk management solution. With instant access to the world\'s largest business credit database, you can proactively monitor your company\'s business risk exposure based on your customers\' business credit profiles. Custom alerts about changes to a company\'s business credit risk can help you protect your company\'s cash flow and minimize potential bad debt write-offs.',
		'call_to_action' => 'Call Us (800) 372-2733',
		'phone' => '(800) 372-2733',
		'sell_on_mobile' => true,
		'bullets' => [
			'Failure Risk',
			'Delinquency Risk',
			'D&amp;B PAYDEX&reg; Score',
			'Maximum Credit Recommendation',
		],
		'compare_bullets' => [
			'Financial statements',
			'Unlimited and continuous access',
			'Custom data archives',
			'Evaluate multiple companies',
		],
		'included' => [
			'24/7 online access',
			'D&amp;B PAYDEX&reg; Score',
			'12 months of alerts',
			'D&amp;B&reg; Rating',
			'D&amp;B&reg; Financial Stress Score',
			'D&amp;B&reg; Delinquency Predictor Score',
			'Business event notifications',
			'Financial statements',
			'Corporate Linkage',
			'D&amp;B&reg; Supplier Evaluation Risk Rating',
			'Unlimited and continuous access',
			'Custom data archives',
			'Evaluate multiple companies',
		],
		'quantity' => [
			[
				'product_id' => null,
				'price_id' => null,
				'count' => 1,
				'short_description' => 'Call for options',
				'price' => [
					'dollars' => null,
					'cents' => null,
				],
			],
		],
	],
];
